#cloud-config
package_update: true
packages:
  - python3-pip
  - libgl1-mesa-glx
  - libglib2.0-0

# write_files:
#   # Docker config
#   - path: /etc/profile.d/docker-config.sh
#     permissions: 0644
#     owner: root
#     content: |
#       export DOCKER_CONFIG=/var/lib/docker/config

#   - path: /etc/systemd/system.conf.d/docker-env.conf
#     permissions: 0644
#     owner: root
#     content: |
#       [Manager]
#       DefaultEnvironment="DOCKER_CONFIG=/var/lib/docker/config"

# runcmd:
#   - |
#     echo "Fetching environment variables..."
#     metadata_vars=$(curl -f -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/attributes/env-vars")
#     if [ $? -eq 0 ]; then
#         echo "$metadata_vars" | tr ',' '\n' > /var/lib/toolbox/env/llm.env
#         echo "Environment variables written to llm.env"
#     else
#         echo "Failed to fetch metadata!"
#         exit 1
#     fi

# # #cloud-config

runcmd:
  - echo "Starting up"
  - docker pull us-central1-docker.pkg.dev/ac215-project-434717/ocr-ner-repo/ocr-ner-image:latest
  - docker run -d -p 8080:8080 --name app us-central1-docker.pkg.dev/ac215-project-434717/ocr-ner-repo/ocr-ner-image:latest

