# PIPELINE DEFINITION
# Name: ml-pipeline
components:
  comp-data-collector:
    executorLabel: exec-data-collector
  comp-data-processor:
    executorLabel: exec-data-processor
deploymentSpec:
  executors:
    exec-data-collector:
      container:
        command:
        - python
        - cli.py
        image: gcr.io/ai-recipe-441518/llm-data-collector:v1
        resources:
          resourceCpuLimit: 500m
          resourceMemoryLimit: 2G
    exec-data-processor:
      container:
        command:
        - python
        - cli.py
        image: gcr.io/ai-recipe-441518/llm-data-processor:v1
pipelineInfo:
  name: ml-pipeline
root:
  dag:
    tasks:
      data-collector:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-collector
        taskInfo:
          name: Data Collector
      data-processor:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-processor
        dependentTasks:
        - data-collector
        taskInfo:
          name: Data Processor
schemaVersion: 2.1.0
sdkVersion: kfp-2.10.1
