name: CI Pipeline

on:
  push:
    branches: [ milestone4 ]
  pull_request:
    branches: [ milestone4 ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ "api-service", "fine-tuning" ]
        python-version: [ "3.11" ]

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install CUDA (optional for GPU support)
      - name: Install CUDA Dependencies
        if: matrix.container == 'fine-tuning'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcudart12 libcublas12
          echo "/usr/local/cuda/lib64" >> $GITHUB_ENV

      # Step 4: Install Python dependencies
      - name: Install Dependencies for ${{ matrix.container }}
        working-directory: src/${{ matrix.container }}
        run: |
          pip install pipenv
          pipenv install --extra-index-url https://download.pytorch.org/whl/torch_stable

      # Step 5: Run tests
      - name: Run Tests for ${{ matrix.container }}
        working-directory: src/${{ matrix.container }}
        run: |
          pipenv run pytest tests/ --cov=. --cov-report=xml --cov-config=.coveragerc

      # Step 6: Upload coverage report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: src/${{ matrix.container }}/coverage.xml
